insert into usuario (Nome, Login, Senha, Gerente) values ('Jomar', 'jomar', '22217149fbeb7b991712fb94859b2d3e', 0)
insert into usuario (Nome, Login, Senha, Gerente) values ('Gerente', 'gerente', '3902c0df5d25ffb8106b777c84f207b4', 1)
insert into produto (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Casamento 1', 1000, 'chique demais 1', 2, 2)
insert into produto (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Casamento 2', 2000, 'chique demais 2', 2, 2)
insert into produto (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Casamento 3', 3000, 'chique demais 3', 2, 2)
insert into produto (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Debutante 1', 1000, 'chique demais 1', 2, 2)
insert into produto (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Debutante 2', 2000, 'chique demais 2', 2, 2)
insert into produto (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Debutante 3', 3000, 'chique demais 3', 2, 2)
insert into produto (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Debutante 4', 4000, 'chique demais 4', 2, 2)
insert into produto (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Debutante 5', 5000, 'chique demais 5', 2, 2)
insert into produto (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Formatura 1', 1000, 'chique demais 1', 2, 2)
insert into produto (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Formatura 2', 2000, 'chique demais 2', 2, 2)
insert into produto (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Formatura 3', 3000, 'chique demais 3', 2, 2)
insert into produto (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Formatura 4', 4000, 'chique demais 4', 2, 2)
insert into produto (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Formatura 5', 5000, 'chique demais 5', 2, 2)
insert into opcional (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Cama Elástica', 300, 'com proteção', 2, 2)
insert into opcional (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Churrasqueira Controle Remoto', 2000, 'TA PEGANDO FOGO BIXO', 2, 2)
insert into opcional (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Dançarinos de Tango', 800, 'Zé e Bergamotina', 2, 2)
insert into opcional (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Dançarinos de Balada', 800, 'Jó, Raissa e Camila', 2, 2)
insert into opcional (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Fotografo', 900, 'Foto Moraes', 2, 2)
insert into opcional (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Garçons', 2200, 'Trages: vermelho, preto, azul, verde e branco', 2, 2)
insert into opcional (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Imitador', 500, 'Michael Jackson, Homem Aranha, Lula', 2, 2)
insert into opcional (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Palhaço', 600, 'Adulto e Infantil', 2, 2)
insert into opcional (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Pirotecnico', 1300, 'Engole fogo, gospe fogo, dança no fogo, pega fogo, apaga fogo', 2, 2)
insert into opcional (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Decoração', 3300, 'Nossa equipe decora a festa para você não ter este traablho', 2, 2)
insert into opcional (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Iluminação Piscante', 600, 'Do Moderno ao Retrô', 2, 2)
insert into opcional (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Atores', 600, 'Atores bonitos e descolados para parecer que sua festa é legal.', 2, 2)
insert into Pacote (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Projeto X', 3300, 'Decoração e Dançarinos de Balada', 2, 2)
insert into Pacote (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Super Projeto X', 3300, 'Decoração, Dançarinos de Balada e Pirotécnico', 2, 2)
insert into Pacote (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Hiper Projeto X', 3300, 'Decoração, Dançarinos de Balada, Pirotécnico e Iluminação', 2, 2)
insert into Pacote (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Mega Projeto X', 3300, 'Decoração, Dançarinos de Balada, Pirotécnico, Iluminação e Atores', 2, 2)
insert into Pacote (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Power Projeto X', 3300, 'Decoração, Dançarinos de Balada, Pirotécnico, Iluminação,  Atores e Churrasqueira Controle Remoto', 2, 2)
insert into Pacote (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Luxo', 3300, 'Decoração e Fotógrafo', 2, 2)
insert into Pacote (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Super Luxo', 3300, 'Decoração, Fotógrafo e Dançarinos de Tango', 2, 2)
insert into Pacote (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Hiper Luxo', 3300, 'Decoração, Fotógrafo, Dançarinos de Tango e Garçons', 2, 2)
insert into Pacote (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Criança Feliz', 3300, 'Decoração e Fotógrafo', 2, 2)
insert into Pacote (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Super Criança Feliz', 3300, 'Decoração, Fotógrafo e Palhaço', 2, 2)
insert into Pacote (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Hiper Criança Feliz', 3300, 'Decoração, Fotógrafo, Palhaço e Imitador', 2, 2)
insert into Pacote (nome, valor, descricao, quantidade, quantidadeDisponivel) values ('Mega Criança Feliz', 3300, 'Decoração, Fotógrafo, Palhaço, Imitador, Cama Elástica', 2, 2)

select * from cliente


